# Generated by Django 3.1.2 on 2020-10-27 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 27, 23, 16, 57, 957353)),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='discount_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
