# Generated by Django 3.1.2 on 2020-11-02 09:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20201028_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 2, 16, 12, 24, 25400)),
        ),
        migrations.AlterField(
            model_name='order',
            name='stage',
            field=models.CharField(choices=[('PROCESSING', 'Processing'), ('SHIPPING', 'Shipping'), ('DONE', 'Done'), ('CANCEL', 'Cancel'), ('RETURN', 'Return')], default='PROCESSING', max_length=20),
        ),
    ]
