# Generated by Django 3.1.2 on 2020-10-21 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20201019_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 21, 22, 1, 26, 455313)),
        ),
    ]
