# Generated by Django 3.1.2 on 2020-10-24 15:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20201022_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 24, 22, 18, 40, 926653)),
        ),
    ]
