# Generated by Django 3.1.2 on 2020-10-25 07:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20201024_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='unit_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='unit_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 25, 14, 34, 58, 991954)),
        ),
    ]
