# Generated by Django 3.1.2 on 2020-10-25 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20201025_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='discount_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='unit_actual_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 25, 23, 8, 23, 579673)),
        ),
    ]
