# Generated by Django 3.1.2 on 2020-10-25 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_auto_20201025_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 25, 23, 34, 40, 288471)),
        ),
        migrations.AlterField(
            model_name='order',
            name='stage',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Shipping', 'Shipping'), ('Done', 'Done'), ('Cancel', 'Cancel')], default='Processing', max_length=20),
        ),
    ]
