# Generated by Django 3.1.2 on 2020-10-27 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='apply_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 27, 23, 16, 57, 954361)),
        ),
    ]
