# Generated by Django 3.1.2 on 2020-11-02 09:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20201028_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='apply_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 2, 16, 12, 24, 19982)),
        ),
    ]
