# Generated by Django 3.1.2 on 2020-10-19 08:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20201013_2325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='manufacturers',
            new_name='manufacturer',
        ),
        migrations.AlterField(
            model_name='discount',
            name='apply_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 19, 15, 12, 18, 856294)),
        ),
    ]
