# Generated by Django 3.1.2 on 2020-10-21 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20201019_1512'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Manufacturers',
            new_name='Manufacturer',
        ),
        migrations.AlterField(
            model_name='discount',
            name='apply_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 21, 22, 1, 26, 449858)),
        ),
    ]
