# Generated by Django 3.1.2 on 2020-10-22 08:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20201021_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='apply_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 22, 15, 20, 35, 585507)),
        ),
    ]
