# Generated by Django 3.1.2 on 2020-10-24 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 24, 22, 33, 58, 237972)),
        ),
    ]
