# Generated by Django 3.1.2 on 2020-10-24 15:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_token_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 24, 22, 50, 10, 631117)),
        ),
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
