# Generated by Django 3.1.2 on 2020-10-25 07:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20201024_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 25, 14, 34, 58, 991954)),
        ),
    ]
