# Generated by Django 3.1.2 on 2020-11-03 04:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20201102_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 11, 34, 27, 952992)),
        ),
        migrations.AlterField(
            model_name='token',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 11, 34, 27, 952495)),
        ),
    ]
