# Generated by Django 3.1.2 on 2020-10-25 16:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20201025_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 25, 23, 22, 31, 576388)),
        ),
    ]
